### ISSUE TITLE
bug: geth Dot/Box network status out of sync with node

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#101]
<img width="461" alt="Screen Shot 2019-03-20 at 8 05 13 AM" src="https://user-images.githubusercontent.com/3621728/54691130-588cc780-4ae8-11e9-834a-334d39439c67.png">

- [x] notifications lost in IPC
- [x] hide peerCount error from UI
- [ ] Dot pulse on new block
- [ ] Dot stale color
- [ ] transition from sync to newHeads subscription
- [ ] properly resume subscriptions
- [ ] handle client errors in UI

**Comment by evertonfraga** [comment]
that does not apply anymore. closing it.
