### ISSUE TITLE
chore: write Mist issue auto-response content

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#105]
- [x] Content
- ~Auto-response mechanism~
- [x] Put message on issue template
- [x] pin issue

**Comment by evertonfraga** [comment]
https://github.com/ethereum/devops/issues/192


I created a [GitHub app for Autoresponder](https://github.com/apps/probot-autoresponder). 

## Additional resouruces
https://github.com/probot/probot/blob/master/docs/deployment.md#now
https://github.com/probot/autoresponder/blob/master/docs/deploy.md
