### ISSUE TITLE
Test plan

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#107]
### acceptance / e2e testing
- spectron + ava

### integration testing
- start with plugin testing
- [todo]

### basic security test
- npm/yarn audit
- eletronegativity

### component testing
- [react testing library](https://github.com/kentcdodds/react-testing-library)

### unit testing
- extract react class methods and unit-test them
- same with grid (shell)

### artefact test
- code signing and installation asserts

### visual regression
- [Argos](https://www.argos-ci.com/mui-org/material-ui)
- [webdriverio integration](https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-applitools-service)

### to think about
- performance test
- mutation test (this is so next level, but i love the idea)
- migration test (upgrading shell and UI)

**Comment by PhilippLgh** [comment]
would have been nice but too resource heavy
