### ISSUE TITLE
As a developer, I want to have a way to share my Grid landing page iteration with my peers, so I don't test them in production.

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#110]
- [ ] Install netlify for static pages preview

**Comment by PhilippLgh** [comment]
@evertonfraga what is the state here?

**Comment by evertonfraga** [comment]
@PhilippLgh the state is _unstarted_. But I can do that today, if that's still relevant.

**Comment by PhilippLgh** [comment]
Would leave assessment of the importance of this to you. Feel free to close if this is rather "nice-to-have"

**Comment by evertonfraga** [comment]
This is certainly a nice to have. Pages can be developed and previewed locally as well. Closing...
