### ISSUE TITLE
Small UI improvements group ticket

### ISSUE THREAD

**Issue by PhilippLgh** [ethereum/grid#111]
- [x] changing the switch without a downloaded client should create toast notification to download first
- [x] the right pane should use the full width and height of the window
- [x] settings fields should be larger so that text fits inside
- [x] checkboxes should be visible even if downloaded binaries are not selected for consistency
- [x] terminal output should be cleared on restart 
- [x] error messages should disappear e.g. when client restarted
- [x] scrollbars should only be shown if necessary
- [x] the tab's disabled state should have better visibility (higher contrast) 
- [x] the data directory setting should open a file browser dialog

**Comment by ryanio** [comment]
marking `error messages should disappear e.g. when client restarted` as completed because in https://github.com/ethereum/grid-ui/pull/35 i added a closable `X` button to the error message snackbar

**Comment by ryanio** [comment]
`terminal output should be cleared on restart` added to https://github.com/ethereum/grid-ui/pull/33/commits/cb087c177754f49b10d9d7c346e99aaf138809b7

**Comment by ryanio** [comment]
`checkboxes should be visible even if downloaded binaries are not selected for consistency` added to https://github.com/ethereum/grid-ui/pull/35/commits/52029f12e870fda81a2c1e1f953c5f02dd99e3e0

**Comment by ryanio** [comment]
`changing the switch without a downloaded client should create toast notification to download first` added to https://github.com/ethereum/grid-ui/pull/35/commits/b5b752cd9b7142afb6764b02b58021d42afd2b1f via help tooltip on hover of disabled switch

**Comment by ryanio** [comment]
`the right pane should use the full width and height of the window`
`settings fields should be larger so that text fits inside`
and
`scrollbars should only be shown if necessary`
added to https://github.com/ethereum/grid-ui/pull/35/commits/bc8d9d24893c9bbc1c7c07856109ef49ba2cfcce

**Comment by ryanio** [comment]
`while the client is starting the activation switch should be disabled` not sure about this one, i think it is fine to leave the switch enabled because they can choose to stop the process even right after starting it if they wish

**Comment by ryanio** [comment]
`the tab's disabled state should have better visibility (higher contrast)` added to https://github.com/ethereum/grid-ui/pull/35/commits/daab803f17ff51e3e9bd93d66041348b1868baa6

**Comment by ryanio** [comment]
`the data directory setting should open a file browser dialog` added to https://github.com/ethereum/grid/pull/118 and https://github.com/ethereum/grid-ui/pull/35
