### ISSUE TITLE
Bug: shell updater menu not displayed

### ISSUE THREAD

**Issue by PhilippLgh** [ethereum/grid#135]

**Comment by marcgarreau** [comment]
Not sure if I grok the task. What I'm seeing is:

1) `yarn start:dev`, the `Updater` menu item is not displayed. This has always been the case if I recall correctly.

2) `yarn start:prod`:
<img width="661" alt="Screen Shot 2019-06-06 at 10 37 08 AM" src="https://user-images.githubusercontent.com/3621728/59042627-08481a80-8838-11e9-995d-175fc749c21b.png">


3) Running the distributed binary: (No "Check Update" option in the first dropdown) 
<img width="655" alt="Screen Shot 2019-06-06 at 10 42 39 AM" src="https://user-images.githubusercontent.com/3621728/59042458-b99a8080-8837-11e9-9504-64ca080113fa.png">

**Comment by evertonfraga** [comment]
I don't see the `Updater` root menu. how weird.
