### ISSUE TITLE
bug: datadir path in windows has wrong slash

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#182]
Geth handles that gracefully and converts forward slashes to back 
<img width="1049" alt="Screen Shot 2019-04-19 at 10 28 50 AM" src="https://user-images.githubusercontent.com/47108/56428753-80f61600-628e-11e9-9470-8dcc0d985aaa.png">
slashes

**Comment by PhilippLgh** [comment]
consistency would be good but don't think this is a bug. windows should be able to handle `/` and the more problematic (and more windows typical) ones are `\` because they need to be escaped and end up as `\\`. so maybe we can agree to sanitize to `/`.
