### ISSUE TITLE
The big, un-prioritized services wishlist

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#194]
### current / soon

| Service name | type | stats | source |
| ------------- | ----- | ----- | ------ |
| geth | ETH 1.0 | ✅| azure |
| parity | ETH 1.0 | ✅| mirror (ev) |
| aleth | ETH 1.0 | ✅ | GH releases |
| swarm | storage | ✅ | azure |
| clef | signer | 🛠| azure |

### research

| Service name | type | binaries | installation method | 
| ------------- | ----- | ----------------- | ------------------- | 
| [trinity](https://github.com/ethereum/trinity) | ETH 1.0/2.0 | ❌| python/docker |
| [ethereumJS](https://github.com/ethereumjs/ethereumjs-client) | ETH 1.0 | ❌| npm |
| [ethereumJ](https://github.com/ethereum/ethereumj) | ETH 1.0 | ❌ | gradle / `java -jar`
| [Nethermind](https://github.com/NethermindEth/nethermind/releases) | ETH 1.0 | ✅ | GH releases
| [Plasma group](https://github.com/plasma-group/plasma-client/) | ETH 2.0 | ❌ | npm |

ETH 2.0
- nimbus
- pegasus
- lighthouse
- kyokan plasma
- prismatic labs
- shasper
- chainsafe's impl.

OTHER
- [Ganache](https://github.com/trufflesuite/ganache-cli)
- IPFS
- whisper (geth flag)

**Comment by PhilippLgh** [comment]
https://github.com/PhilippLgh/ethereum-binaries/issues/3
