### ISSUE TITLE
List of public network and chain IDs

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#201]
| ID | Network |
| -- | -------- | 
| 0 | Olympic, Ethereum public pre-release PoW testnet |
| 1 |  Frontier, Homestead, Metropolis, the Ethereum public PoW main network |
| 1 |  Classic, the (un)forked public Ethereum Classic PoW main network, chain ID 61 |
| 1 |  Expanse, an alternative Ethereum implementation, chain ID 2 |
| 2 |  Morden Classic, the public Ethereum Classic PoW testnet |
| 3 |  Ropsten, the public cross-client Ethereum PoW testnet |
| 4 |  Rinkeby, the public Geth-only PoA testnet |
| 5 |  Goerli, the public cross-client PoA testnet |
| 6 |  Kotti Classic, the public cross-client PoA testnet for Classic |
| 8 |  Ubiq, the public Gubiq main network with flux difficulty chain ID 8 |
| 42 |  Kovan, the public Parity-only PoA testnet |
| 60 |  GoChain, the GoChain networks mainnet |
| 77 |  Sokol, the public POA Network testnet |
| 99 |  Core, the public POA Network main network |
| 100 |  xDai, the public MakerDAO/POA Network main network |
| 31337 |  GoChain testnet, the GoChain networks public testnet |
| 401697 |  Tobalaba, the public Energy Web Foundation testnet |
| 7762959 |  Musicoin, the music blockchain |
| 61717561 |  Aquachain, ASIC resistant chain |
| [Other] |  Could indicate that your connected to a local development test network. |

https://ethereum.stackexchange.com/questions/17051/how-to-select-a-network-id-or-is-there-a-list-of-network-ids

**Comment by Tectract** [comment]
https://chainid.network/
