### ISSUE TITLE
As a user, I want to be notified when a new version of my node is available, so I don't fork.

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#22]

**Comment by ryanio** [comment]
An idea for this, maybe we can have a notification area above VersionList that if the selected release is older than the latest remote version, it can say something like

```
<!> You are using an older version of geth (1.2.2)
New releases contain performance and security enhancements.
Click here to download|use the newest version (1.2.3)
```

Another nice feature could be an advanced settings checkbox that says "Always download and use the latest version of geth". On `VersionList` component load it could auto download and select the newest version.
