### ISSUE TITLE
As a user, I want to have the connection details remembered, so I can have a consistent use of the app

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#23]

**Comment by ryanio** [comment]
I think for this all we will need to do is install `redux-persist` and have it configured properly, since the redux config state details are saved to geth before `start()`

**Comment by ryanio** [comment]
Also implementing HMR with `redux-persist`: https://github.com/rt2zz/redux-persist/blob/master/docs/hot-module-replacement.md

**Comment by evertonfraga** [comment]
I guess this is not implemented, or we had a regression due to the latest plugin changes. Reopening.
