### ISSUE TITLE
external: download Parity-hosted binaries

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#241]

**Comment by evertonfraga** [comment]
Consider using those version lists:

https://vanity-service.parity.io/parity-binaries

http://releases.parity.io

**Comment by evertonfraga** [comment]
@PhilippLgh can any of those feeds be used with the App Updater?

it seems there are some variables to tweak to get more specific results: https://vanity-service.parity.io/parity-binaries?version=v2.5.1
