### ISSUE TITLE
As a user, I'd love to know how to connect with the services I start, so I can take more advantage of what Grid has to offer.

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#253]

**Comment by marcgarreau** [comment]
what does this mean/look like @evertonfraga?

**Comment by evertonfraga** [comment]
this user story got more complex with the dynamic plugin architecture. the
initial idea was to display a pane after node has started instructing the
user. example:

“You have started Geth.

Here are some ways to use it:

- You can connect with MetaMask using https://localhost:8545
- Use console with command `geth —datadir ~/privatenet console”

i’d argue this can be done when we make an “UI audit”, because there are
lots of ways to aid the user.
