### ISSUE TITLE
As a user, I want to use Prysm in Grid in a intuitive way, so I can be part of the ETH 2.0 movement

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#261]
See discussion https://github.com/PhilippLgh/ethereum-grid-tutorials/issues/2

#### Running 
- [ ] Include required flags

#### Fetching from original repo
- [ ] Allow dynamic binary name — prysm contains version number on file name
- [ ] Allow fetching github pre releases
- [ ] Allow unpackaged binaries

**Comment by PhilippLgh** [comment]
implemented by: https://github.com/PhilippLgh/ethereum-binaries
