### ISSUE TITLE
feature idea: decentralized block explorer

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#266]
spike: [TrueBlocks](https://github.com/Great-Hill-Corporation/trueblocks-core)

**Comment by tjayrush** [comment]
Hi guys. I found you through some weird tweet somewhere. Love that the first visit to your GitHub, I find this. I work on TrueBlocks. Love to learn more about your project. I'll look for a discussion link and and join you there.

**Comment by marcgarreau** [comment]
Thanks for reaching out @tjayrush. Actually, we met briefly at ETHDenver this year while searching for teams 😎 We don't have a public telegram/discord server set up yet, but we'll get that started soon.

I've barely had a chance to take a look at TrueBlocks, but saw the recent release announcement and thought a block explorer would make a ton of sense within Grid. Look forward to learning more about the project and discussing an integration.
