### ISSUE TITLE
Unable to build grid / grid-ui

### ISSUE THREAD

**Issue by prestonvanloon** [ethereum/grid#271]
I ran yarn && yarn start:dev

```
error https://registry.yarnpkg.com/@babel/helper-plugin-utils/-/helper-plugin-utils-7.0.0.tgz: Integrity check failed for "@babel/helper-plugin-utils" (computed integrity doesn't match our records, got "sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==")
```

**Comment by evertonfraga** [comment]
That seems like a yarn bug. Are you able to update it and try again?

```
 curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
```

I saw some people with similar problems, but they seemed to use private package registries, which is probably not your case.

**Comment by evertonfraga** [comment]
Also, consider removing `node_modules` directory and running `yarn` again.

**Comment by prestonvanloon** [comment]
Thanks. I updated yarn, did `yarn cache clean`, deleted node modules, rebooted my computer, had some more coffee.

Builds now :+1:

**Comment by prestonvanloon** [comment]
Resurrecting this. I did get it to build previously, but had no success actually using it. 

When I run the commands as described in the README, the UI appears on port 3080, but it is empty. The console has an error connecting to the websocket 

```
sctransport.js:14 WebSocket connection to 'ws://localhost:8000/socketcluster/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

The grid repository seems to be running in another terminal, but I have some errors that do not look great. 

```
➜  grid git:(master) yarn && yarn start:dev
yarn install v1.16.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.42s.
yarn run v1.16.0
$ cross-env NODE_ENV=development electron .
plugin init: 21.938ms
0 remote plugins found
(node:32293) UnhandledPromiseRejectionWarning: timeout
(node:32293) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32293) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a
non-zero exit code.
updater cannot be executed on unsigned applications - routine cancelled
```

Not sure how to proceed here. Please help, thanks!

**Comment by evertonfraga** [comment]
> UI appears on port 3080, but it is empty. 

The page that opens on the browser can be safely ignored. grid-ui's front-end should only be loaded from Grid. We just merged a small PR preventing website from opening automatically: https://github.com/ethereum/grid-ui/pull/92

Please update grid-ui from `dev` branch and let us know

I believe the cryptic unhandled exception is given when no connection to the grid-ui is found. was `grid-ui` started when you got that?

**Comment by evertonfraga** [comment]
should you encounter any issues again, let us know!
