### ISSUE TITLE
grid-rpc-app: convert hex result to number

### ISSUE THREAD

**Issue by ryanio** [ethereum/grid#278]

**Comment by evertonfraga** [comment]
might be useful to still present the raw values, to prevent confusion.

**Comment by ryanio** [comment]
yeah, I’m not quite sure how to execute on this yet. open to ideas. I was thinking maybe a button to toggle or converting on hover.

but I am also not sure yet how to determine if a value is a hex value that’s meant to be represented as a number. will investigate.
