### ISSUE TITLE
Service actions

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#280]
Actions are short-lived operations started from a client/tool. it should take parameters and have an stdout that should be passed back to the user. Examples:
- `geth removedb` (no params)
- `geth init genesis.json` (file on path)
- `geth removedb --datadir ~/.ethereum/privatenet` (reusing user config values from settings tab)

#### Requirements
- Clients can specify which actions they support
- Clients can specify which options can be reused on the command
- Users should be able to stop/interrupt an action
- Actions could be run even with the service started

#### TBD
- how should the output of actions be displayed?

**Comment by ryanio** [comment]
This all sounds great.

Related to https://github.com/ethereum/grid/issues/307

**Comment by marcgarreau** [comment]
Closing; as discussed, the infrastructure/API is in place. Additional tickets have been opened for the UI.
