### ISSUE TITLE
As a user, I want to install plugins from third-party sources

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#281]
User stories: 

### Plugins (services)
- As a user, I want to add a new registry URL for plugins
- As a user, I want to view all services, from all registries, on my sidebar (1st iteration)
- As a user, I want to select which services should be displayed on my sidebar (2nd iteration)
- As a user, I want to search/filter packages from all registries (2nd iteration)
- As a user, I want an easy way to reload / refresh my plugins without having to restart the application

### Apps 
- As a user, I want to add a new registry URL for apps
- As a user, I want to view all apps, from all registries, on my App list (1st iteration)
- As a user, I want to select which apps should be displayed on my App list (2nd iteration)
- As a user, I want to search/filter Apps from all registries (2nd iteration)

**Comment by PhilippLgh** [comment]
https://github.com/ethereum/grid/pull/293
