### ISSUE TITLE
As a user, I want to be able to copy and paste anywhere on Grid app

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#299]
That is expected from any desktop app, we should not forget to add support in grid as well.

- [ ] right click > cut / copy / paste / select all
- [x] keystroke > `(Control|Cmd)-[XCVA]`
- [x] edit menu > cut / copy / paste / select all

**Comment by ryanio** [comment]
I think this may be what we need https://www.codedmaster.com/2017/01/24/getting-electron-copy-paste-shortcuts-for-mac-builds/
