### ISSUE TITLE
As a user, I want nano to live alongside its icon, so I can tell its coupled

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#334]
e.g. in Linux, nano is stuck to the top-right, while the tray icon is on the bottom of the screen.

Alternatively, allow nano to be decoupled and dragged around.

**Comment by PhilippLgh** [comment]
this is a potential `wontfix` since electron does not reliably provide the tray's position on all platforms. it requires platform API's and native code and even then we might run into edge cases. drag + position persistence is probably our best attempt

**Comment by evertonfraga** [comment]
1.5.1 might not use nano, so removing it for now.

**Comment by evertonfraga** [comment]
Adding more context to the conversation.

There are several desktop environments available around, with a number of possibilities for customization. On my research

| | GTK3 | KDE |
|--------|-------|--------|
| By default | top | bottom |
| Possible to configure | only top | top + bottom |
