### ISSUE TITLE
When Grid-ui goes full screen, nano also shows in full screen (macos)

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#342]

**Comment by ryanio** [comment]
BrowserWindow has a `maximizable` property that works for mac and win so I tested passing it as `false` into the menubar browserwindow options in the constructor in `nano.js` and I was still able to get mac to maximize the window after going full screen on grid-ui then clicking the grid icon in the toolbar.

https://electronjs.org/docs/api/browser-window#new-browserwindowoptions

Might be worth a PR anyway if it helps other cases, or if it works on windows.

**Comment by evertonfraga** [comment]
maybe we should use the `fullscreenable` option for that

**Comment by evertonfraga** [comment]
Closed by #410
