### ISSUE TITLE
Bug: custom flag overrides are persisted but not displayed on reboot

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#352]

**Comment by ryanio** [comment]
I'm not able to recreate, can you explain steps to recreate the issue? Thanks

**Comment by marcgarreau** [comment]
@ryanio yup, workflow used to discover it:
- run `yarn start:dev` > open grid-ui
- navigate to Geth settings > edit flags > add something arbitrary (`--welp` in my case)
- click away/kill the app
- run `yarn start:dev`, run Geth from nano
- in terminal window running Grid, observe errors including `'Incorrect Usage. flag provided but not defined: -welp'`
- open grid-ui > Geth settings > see that edit flags input field does not include `--welp`

**Comment by ryanio** [comment]
Following your workflow, after toggling off the app from grid-ui, nano kept showing it as on in `starting` state. We may have other regressions here.

<img width="1091" alt="Screen Shot 2019-07-21 at 9 23 38 PM" src="https://user-images.githubusercontent.com/22116/61606179-da5b4180-abfd-11e9-8457-1709f92aab1c.png">

---

I think in `client:init` we need to rehydrate `flags` from `config.json` if exists: https://github.com/ethereum/grid-ui/blob/c5eb4121d3b1ca528a132cbee778503f26fad21d/src/store/client/actions.js#L50

**Comment by marcgarreau** [comment]
Yep, re: rehydrate flags. 

And yes, this "out of sync" observation is the same one I made last week. When starting with a busted flag, nano interprets a successful start, while grid-ui does not. I suppose that deserves its own ticket.

**Comment by ryanio** [comment]
Ok I will work on a PR for rehydrating flags

**Comment by marcgarreau** [comment]
Closed by https://github.com/ethereum/grid-ui/pull/110
