### ISSUE TITLE
Bug: nano doesn't respect plugin display order settings

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#364]
<img width="428" alt="Screen Shot 2019-07-23 at 10 50 04 AM" src="https://user-images.githubusercontent.com/3621728/61731150-15619000-ad38-11e9-996c-6eb70e12e388.png">

**Comment by ryanio** [comment]
We'll have to sync up the logic between the two. 

Right now in grid-ui, it creates keys out of categories then sorts the plugins within the categories order ascending.  However there is no specified sort on the categories, maybe we should do alphabetical?

Then in nano we can do category (alphabetical) => plugin (order asc)

**Comment by PhilippLgh** [comment]
the order info is quite problematic and broken. if we allow user-defined plugins and external sources this info will become meaningless as everyone probably wants to be positioned as #1. a better approach is what @ryanio proposes

**Comment by ryanio** [comment]
yes, we could (or maybe should) also have user drag-droppable order, maybe within the predefined categories
