### ISSUE TITLE
Make better use of logging

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#371]
We've been using logging for things that are on our plate, then we remove them when we consider the feature/bugfix done.

That does not help when we need detailed reports from users. I propose we make a better use of logs, considering that we don't expect our users to debug the app using VSCode.

- [ ] use log levels for (debug, trace, info, warn)
- [ ] enable log output by module
- [ ] ability to start app with a loglevel set, via command line flag and shortcut (windows)

![image](https://user-images.githubusercontent.com/47108/61968916-37147e80-afa7-11e9-9f10-7873edc7eec1.png)

**Comment by ryanio** [comment]
I liked using https://www.npmjs.com/package/debug, but it doesn't have log levels.
