### ISSUE TITLE
Disappearing icon in windows

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#379]
@PhilippLgh reported this issue still happens during his tests.

I suspect of other electron apps with the same default identifier. we can test some different combinations of fixes having those open:
- discord
- keybase
- skype
- slack

**Comment by evertonfraga** [comment]
@PhilippLgh found out his overflow menu is actually opening behind the taskbar, therefore, hiding grid icon
![image](https://cdn.discordapp.com/attachments/483981458705350658/605412151359700997/unknown.png)

**Comment by evertonfraga** [comment]
That'll be a wontfix, i'm afraid. several other cases from people around. We should inform this on the release notes: 

https://superuser.com/questions/1335376/show-hidden-icons-menu-hidden-behind-taskbar
https://answers.microsoft.com/en-us/windows/forum/windows_10-start-win_tray/show-hidden-icons-popup-is-cut-off-by-taskbar/1564123a-6fa3-47c7-92a8-aaf6bb9cbe48

**Comment by PhilippLgh** [comment]
updating display drivers fixed that one
