### ISSUE TITLE
As a user, I want to see release notes, so that I understand what changes I am installing

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#452]

**Comment by ryanio** [comment]
Added to geth here: https://github.com/ethereum/grid/pull/453

Added to clef here: https://github.com/ryanio/grid-clef-plugin/commit/f52fdea64e9fda95911d26e79349f7150a04eaaf

Would be useful to have it in a handful of the other default plugins.

IPFS: https://github.com/ipfs/go-ipfs/blob/master/CHANGELOG.md

**Comment by marcgarreau** [comment]
wups - sorry, just saw you were using this for multiple. let's create new tickets for additional updates? if you disagree, feel free to reopen. just looking to prevent it from sitting in the `review` column for a long stretch.
