### ISSUE TITLE
Restrict / harden the release process

### ISSUE THREAD

**Issue by PhilippLgh** [ethereum/grid#5]
The release process should be as simple as possible but also not sacrifice security for convenience.
We should probably have a constraint that new releases that trigger auto-update require a 2nd reviewer to avoid accidentally released versions or attacks.

**Comment by evertonfraga** [comment]
Alright, I'll configure CircleCI with a special feature I wanted to test.

**Comment by PhilippLgh** [comment]
Won't be possible without necessary resources
