### ISSUE TITLE
Add Tor/i2p node launchers

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/grid#502]
It would be neat if there was support for running [Tor](https://www.torproject.org/) and/or [I2P](https://geti2p.net/) routing nodes. Both of them have Docker images and relatively easy configs.

**Comment by evertonfraga** [comment]
that's a good idea! 

once we implement the docker executor type, we'll open a huge opportunity window for tons of services.

**Comment by PhilippLgh** [comment]
the binary management and the grid desktop app got separated into different modules. there is a new project for binary management `ethereum-binaries` that *finally* has docker support and can be used standalone or by other applications. if there will be future releases of a grid desktop app they will use this module. I put Tor and I2P on the wishlist so if this is still desired please give them an upvote here: https://github.com/PhilippLgh/ethereum-binaries/issues/3
