### ISSUE TITLE
blog post: how to use Remix Desktop and Grid for a local geth dev environment

### ISSUE THREAD

**Issue by ryanio** [ethereum/grid#503]

**Comment by ryanio** [comment]
Have begun work here: https://medium.com/p/6a1c7d9cf666/edit

**Comment by PhilippLgh** [comment]
@ryanio don't know how to proceed here

**Comment by ryanio** [comment]
I still have this blog post in a final draft form so I will close this issue for now but happy to revisit it in the future.
