### ISSUE TITLE
Block explorer: Whoops! Something went wrong

### ISSUE THREAD

**Issue by gpersoon** [ethereum/grid#510]
When I start the blockexplorer (without the graphql) I get an error message.
```JS
Whoops! Something went wrong.
This error is unaccounted for. Check the logs and file an issue, please!
```

In the development console I see:
```
error during require of electron modules Cannot read property 'getVersion' of undefined
C:\Users\gerar\AppData\Local\Programs\grid\resources\app\node_modules\@philipplgh\electron-app-manager\dist\updater\AppManager.js:34
```
#### Reproduce 
Download and install https://github.com/ethereum/grid/releases/download/v1.6.2/Grid-Setup-1.6.2.exe
Select Geth
Start Geth  (with default options)
Start Block Explorer

#### Details:
OS: Windows 10
Grid Version: Grid-Setup-1.6.2.exe
Geth Version: Geth V.1.9.7 64 bit

**Comment by marcgarreau** [comment]
I've bumped "better error handling" up on the priority list. Thanks for reporting, and using Grid :)
