### ISSUE TITLE
Block explorer: Oh no! Your node is lonely.

### ISSUE THREAD

**Issue by gpersoon** [ethereum/grid#511]
When I start the blockexplorer (with graphql & just after geth is started) and then click on the first block: the blocks are empty and the following error is shown:
```JS
Oh no! Your node is lonely.
Your node is having trouble finding peers to get the data it needs. Give it more time, or a restart.
```
I cannot go back to the previous screen. The only option is to stop the block explorer and start it again. If I wait a little while, till geth has received some blocks, then the blocks are accessible.

In the development console I see:
```
error during require of electron modules Cannot read property 'getVersion' of undefined
C:\Users\gerar\AppData\Local\Programs\grid\resources\app\node_modules\@philipplgh\electron-app-manager\dist\updater\AppManager.js:34
```

Probably related to: https://github.com/ethereum/grid/issues/510
#### Reproduce 

Download and install https://github.com/ethereum/grid/releases/download/v1.6.2/Grid-Setup-1.6.2.exe
Select Geth
Start Block Explorer
Click ok (to start Geth with graphql & corsdomain)
Click on block #1 

#### Details:
OS: Windows 10
Grid Version: Grid-Setup-1.6.2.exe
Geth Version: Geth V.1.9.7 64 bit

**Comment by marcgarreau** [comment]
While not obvious, the refresh shortcut will work in this window, e.g. `ctrl+R` in Windows. Regardless, this app requires better error handling. Thanks for reporting.

**Comment by marcgarreau** [comment]
Just published a new release of the block explorer that shows peer count errors inline, so you can continue trying to use the app.
