### ISSUE TITLE
Geth nitpicks

### ISSUE THREAD

**Issue by karalabe** [ethereum/grid#512]
- Version numbers usually start with a lowercase `v`
- I'm unsure if it's a good idea to list 32 bit downloads. A 32 bit binary by definition can only access 4GB of RAM (or 2, depending on OS), which is generally fairly little for mainnet. As such, my suggestion would be to never even offer the user the possibility to install 32 bits on a 64 bit platform (and to warn them on 32 bit ones that it's not suitable for mainnet).

![Screenshot from 2019-11-08 15-37-22](https://user-images.githubusercontent.com/129561/68480602-e36c2f00-023d-11ea-8f09-b8276178d3a5.png)

---

This is a harder nut to crack: If I switch the network from mainnet to Rinkeby, the UI leaves the default datadir in place (`~/.ethereum`), which is wrong (it should be `~/.ethereum/rinkeby` (same for the keystore)).

My suggestion would be to not set these two folders by default, unless the user overrides them explicitly. That way Geth can remain smart and use its default locations. 

![Screenshot from 2019-11-08 15-42-30](https://user-images.githubusercontent.com/129561/68480843-6ee5c000-023e-11ea-9c71-e51a5e482d21.png)

**Comment by marcgarreau** [comment]
thanks for testing and reporting. we'll clean those up shortly.

**Comment by ryanio** [comment]
@evertonfraga if we can keep dataDir and keystoreDir fields in settings but have it default be empty and not pass the flag in if empty, that would be a good solution

**Comment by PhilippLgh** [comment]
captured here: https://github.com/ethereum/grid/issues/538
