### ISSUE TITLE
Clef listing contains duplicate entries?

### ISSUE THREAD

**Issue by karalabe** [ethereum/grid#513]
Something seems really off here.

![Screenshot from 2019-11-08 15-49-31](https://user-images.githubusercontent.com/129561/68481284-778ac600-023f-11ea-9ede-ec98021e8c54.png)

**Comment by karalabe** [comment]
Actually, just blindly starting Clef without downloading any of the suggested versions will download an incompatible one and fail starting with `clef: Syntax error: word unexpected (expecting ")")`

**Comment by PhilippLgh** [comment]
captured here: https://github.com/PhilippLgh/ethereum-binaries/issues/2
