### ISSUE TITLE
Out of sync toggle buttons

### ISSUE THREAD

**Issue by karalabe** [ethereum/grid#515]
When starting Clef, it takes a few seconds after I click on the toggle, before it starts (why?). If during this time I click a second time, a second Clef is started (which fails with a port clash error). The second Clef dying, Grid untoggles the button, but one version is still running (logs are still coming). I have to kill all processes from the console before I can geth Grid back into a consistent state.

**Comment by marcgarreau** [comment]
Haven't dug into the startup delay yet, but the category of double-click bugs should be addressed in the next release by a couple freshly merged commits (https://github.com/ethereum/grid/commit/a428cc19962ee64081aa11bb54e42f0de7a5601a, https://github.com/ethereum/grid-ui/commit/8b87612c01085dea5dc2e8e5fccd2648f3a14ac7). tl;dr - once clicked, buttons are disabled until they shouldn't be.
