### ISSUE TITLE
Client list display improvements

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#517]
Currently, there's a lot of responsibility delegated to the app manager regarding the display of a versionList, especially wrt processor architecture. 

https://codepen.io/evertonfraga-the-animator/pen/YzKMVEa?editors=0012

I propose the following: 
- [ ] client config: file name regex
- [ ] client config: display template
- [ ] provide sensible defaults so not all client plugins should provide its own regex/template config pair

**Comment by evertonfraga** [comment]
Considering that Multi-geth has a different naming system as geth — they don't put the version on the package name, we should consider to extend that format and provide more information to the `format` function

**Comment by PhilippLgh** [comment]
potentially fixed here: https://github.com/PhilippLgh/ethpkg/commit/be40380cc96294c40d07ee51c52713198e6a4613
