### ISSUE TITLE
Core Refactoring

### ISSUE THREAD

**Issue by PhilippLgh** [ethereum/grid#519]
## PR
https://github.com/ethereum/grid/pull/524

## Related Issues describing the vision
https://github.com/ethereum/grid/issues/315
https://github.com/ethereum/grid/issues/445

## Changes
- Architecture: https://github.com/ethereum/grid/issues/523
- Workflows: https://github.com/ethereum/grid/issues/525
- Changes to Plugin: Client and ClientManager #520 
- Changes to Plugin: Replace ClientManager plugin with workflow: https://github.com/ethereum/grid/issues/526
- Changes to API and RPC server: https://github.com/ethereum/grid/issues/522
- Grid-Core module: https://github.com/PhilippLgh/grid-core

All necessary JavaScript files are ported to Typescript in the process.

### Electron App Manager
- [ ] migrate all backend / repo logic to `ethpkg` (80%)
- [ ] migrate all release management logic to `ethpkg` (50%)
- [ ] migrate all app loading logic to `app-package-server` 

### Grid
- [X] port Plugins to typescript
- [X] migrate PluginHost into PluginSystem in `grid-core`
- [X] port `ControlledProcess` to typescript 
- [ ] refactor `Plugin` to `Client` and `ClientManager` (80%)
- [ ] replace PluginHost occurrences with `grid-core` (50%)
- [ ] create simple RPC wrapper to replace injected API (20%)
- [ ] create json-rpc http server (10%)
- [ ] create websocket server for events (0%)
- [ ] port AppManager logic to `app-package-server` (0%)

### Starting Nano
Nano is the menubar UI. It is not packaged or updated independently at the moment. Refactoring nano to React and merging it into grid-ui is probably not part of `v2`
Nano should be able to start even without the API server (immediate user feedback) and implement a mechanism to connect to other servers without reload. 

![image](https://user-images.githubusercontent.com/4280481/69058973-eec91280-0a14-11ea-90f1-cc093b06f3d1.png)

Please note that the API server could also be a list of connection which when clicked on display the state of a remote machine.

### Plugin Init
`grid-core` starts by initializing plugins.
This is a 2 step process:
- local plugins i.e. scanning the file system
- remote plugins: parsing registries & fetching packages
Because this has the potential to take quite long we will use events to inform about the state.

### API Server
Next, `grid-core` will start the the API server. The grid-electron app should check if the API is already available and if not can start the server is necessary.
The API server implements json-rpc and allows `grid-electron` but also other consumer such as `remix-grid-plugin` to query the state of existing and running binaries and make requests to interact.

### API-READY
Once the plugins are initialized and the API is available, Nano will start with a query to:
`getAllClientManagers()`
The `ClientManager` instances are initialized based on plugin information and represent all `Clients` i.e. available and running binaries to interact with.

In UI-terms, a ClientManager will e.g. create an entry for `Geth` even if no local binary is available. Note that this entry will also have a start button in the UI. If multiple clients of the same type are run such as validators the UI should expand into something like a tree-view to show all `Geth` or `CLIENT` instances.

Nano will query each `ClientManager` for available and running clients with:
`clientManager.getAllClients()`. Each client has it's own state and lifecycle stat needs to be reflected in the UI. Moreover, each react-client-item should assign listeners and observe state changes of the Client that need to be reflected.

A common case is that a ClientManager instance only represents one Client. In this case, the tree-view listing all clients can be collapsed and the state info displayed inline on the header.

![image](https://user-images.githubusercontent.com/4280481/69043211-e829a380-09f2-11ea-88ce-34fae59f91c6.png)

**Comment by evertonfraga** [comment]
Nitpick: it's better to use `127.0.0.1` instead of `localhost`, because it's independent to the hosts config of each user.

**Comment by PhilippLgh** [comment]
**Update:** grid-core failed to achieve and implement all of the above ideas in a single module. This is largely due to the fact that it tried to solve multiple disconnected problems:
- plugins and their security are a big challenge best handled by a separate module. However, we will close the public plugin API in Grid which will free a lot of resources for more important things. The community was not involved and the docs for plugins were lacking behind therefore never creating any value.
- workflows simplify interaction with binary management for **end users**, but they don't take away the need to e.g. programmatically interact or manage binaries on a lower level
- an API around binary management be it http or Electron IPC based is best implemented as a wrapper by the projects using binaries but introduces many dependencies, security problems and creates tight coupling

`grid-core` will be deprecated and the binary management will be handled by: https://github.com/PhilippLgh/ethereum-binaries

the http proxy concept might find its way into a new grid release
