### ISSUE TITLE
Changes to Plugin (ClientManagerPlugin)

### ISSUE THREAD

**Issue by PhilippLgh** [ethereum/grid#526]
# Plugins v1

In Grid v1 the only way for clients to be available in the application is by defining a client(manager) plugin first and registering it with the application which requires a start / restart.

Plugins can be loaded in various ways:
- Grid maintains a list of its own plugin files here:(https://github.com/ethereum/grid/tree/master/ethereum_clients/client_plugins) 
- Grid also has a list of externally hosted and maintained plugins defined in `plugins.json` for independent updates
- Registries aka externally hosted `plugins.json` files (experimental)

Client plugins define flags for their client binary as settings objects with additional metadata. Grid can use this description to generate the settings UI based on this config: https://github.com/ethereum/grid-ui/tree/dev/src/components/Plugins/PluginConfig/DynamicConfigForm

Settings Object Example:
```
   {
      id: 'graphql',
      label: 'Enable GraphQL Server',
      default: 'false',
      options: [
        {
          value: 'true',
          flag: '--graphql --graphql.corsdomain=*',
          label: 'Yes, All Origins (*) (Requires Geth >=v1.9.0)'
        },
        { value: 'false', flag: '', label: 'No' }
      ]
    }
```

Rendered Settings + Flag Preview:
![image](https://user-images.githubusercontent.com/4280481/69879448-c3251280-12c7-11ea-9b87-446bbff00dbe.png)

## Problems
While this approach is very flexible it still came with a list of problems:
- Grid core plugins are tightly coupled to main application's release cycle. They can only be updated with new releases
- Externally hosted plugins are very flexible and powerful but pose security issues if unsigned or signed by untrusted entities
- Security comes at a maintenance cost because the release process is not well documented, the tools experimental and the process involves many (complex) steps - such as key management
- Grid only understands flags that are defined in the plugin: for everything else the fallback is the `flag preview` input field
- Flags / settings are not versioned: grid does not know for example if the graphql flags work for geth v1.5 or >=1.9
- Unclear responsibility if `grid` or `grid-ui` should be responsible to turn settings objects into flags
- No easy way to pass raw flags to clients during plugin development
- Hard for external teams e.g. prysm to contribute because they had to learn about plugin-setting-definitions which is not sufficiently documented and was changing quite often due to new scenarios

A big problem in general is the fact that the flag API's don't follow standards and each client supports different flag names + combinations. Some have convenience flags like `--dev` that combine multiple settings behind one flag and are thereby comparable to "profiles".

# Plugins v2

I suggest for Grid v2 two big changes:
1) **remove the settings array from plugins**
2) **slowly phase out the concept of ClientManager plugins**

I've added a new API to grid-core: `createClientManager(config: ClientManagerConfig)`.
Typescript makes it easy to define and document supported fields:

```
export interface ClientManagerConfig {
  name: string;
  repository: string;
  filter?: {
    name: {
      includes?: Array<string>;
      exclude?: Array<string>;
    }
  };
  prefix: string;
  binaryName?: string;
  unpack: boolean;
  about?: {
    description?: string;
  };
}
```
This method makes it easy to define "plugin" logic on the fly and integrate new clients in Grid without having to define and publish a plugin. This API can be used in workflows so that in order to use a new client in a workflow contributors don't have to maintain two plugins.

For the settings I suggest we create **one massive json / js object file** that is hosted on the grid/grid-core repo and fetched by the client.

This file will make it easy for client implementers to contribute through PRs and to uncover problems in API names and different flags.

Example (no real values)
```
  dev: {
    'geth@>=1.2.0': '--dev,
   'parity@1.0.0':  '--config dev'
  }
```

The structure could look like this where we assign aliases for the most common flags or groups of flags and maintain them in a versioned fashion.

Since this file will be fetched on every start it always reflects the latest changes and only requires one request. We also take the burden from plugin developers because they have a good reference of all supported operations and can focus on the client / workflow logic instead of redefining settings objects for their own plugins.

The metadata to generate the UI for these flags can be maintained separately to have a clean structure and reference.

**Comment by marcgarreau** [comment]
Agree with all described existing problems and don't object to the suggested updates, with one caveat: I'm unclear on the scope/goal of the json/js file. If I'm interpreting it correctly, it looks like it could quickly become unwieldy.

* One of the described problems was that we're resorting to the custom flag field for anything we don't handle explicitly. Is this new file meant to address that? i.e. be exhaustive and contain all flag possibilities?
* The `dev` key in the example implies that we'll look for commonalities in function between each client to put in groups? If true, may be a large manual effort on either us or plugin owner - scanning each flag for whether it belongs in a group. (Also assumes exhaustiveness from the first Q)
* The current settings array captures valuable metadata - maybe most notable is how we display settings in human readable format and good defaults. If that doesn't have a home in the new file somewhere, I like to think we can still use it elsewhere if users need to tweak a plugin used in a workflow or run a standalone instance of a plugin. I guess that begs a further question: will we allow workflows to be tweaked by the user, and if so, how?

**Comment by ryanio** [comment]
As I've been [learning Github Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions), I find defining steps in a workflow incredibly flexible and think @PhilippLgh you nailed it on the head.

> For the settings I suggest we create one massive json / js object file that is hosted on the grid/grid-core repo and fetched by the client.

As Marc mentions this might get unwieldy quickly. Settings have always been some of our trickiest configuration challenges. What if we define `workflows` as a series of `steps`, where customization taking into account settings can happen along the way.

We always agreed profiles would be incredibly handy, and a grid workflow could be like defining a profile once. Isolating it in a single file allows for others to easily use/share/modify.

Here is a sample yaml file of a Github Action, the file name can be anything: [vm-test.yml](https://github.com/ethereumjs/ethereumjs-vm/blob/8f6047066e2234934633f69c0507abcca0e160bf/.github/workflows/vm-test.yml)

**Comment by PhilippLgh** [comment]
**update:** 
- plugins are weakened to `ClientConfig` which can be directly used to describe the client "on the fly": `public async getClient(clientSpec: string | ClientConfig, ...)` in [ethereum-binaries](https://github.com/PhilippLgh/ethereum-binaries)
- the individual client settings info remains a large issue and is outside the scope of this issue
