### ISSUE TITLE
The application “Grid” can’t be opened.

### ISSUE THREAD

**Issue by samajammin** [ethereum/grid#530]
Hey folks. Having trouble using the app:

<img width="596" alt="Image 2020-02-19 at 5 18 08 PM" src="https://user-images.githubusercontent.com/8097623/74891842-dd0d4900-533c-11ea-9b8e-8d5926df988a.png">

Version from the site:
Mac | Grid-1.6.2-mac.zip

I'm running:
macOS Catalina
Version 10.15.2

I tried the [1.5.1 release](https://github.com/ethereum/grid/releases/tag/1.5.1) as well. Same issue.

**Comment by marcgarreau** [comment]
Confirmed on my machine. Not sure why the zip download is broken, but you should have success with the .dmg option. Let me know.

**Comment by samajammin** [comment]
Great, thanks @marcgarreau! Downloading the .dmg option got around that issue. Perhaps you should remove that zip option from the website 😅 

FYI, when I download, move to Applications, then double-click to open I see this:
<img width="431" alt="Image 2020-02-20 at 8 05 14 AM" src="https://user-images.githubusercontent.com/8097623/74954437-facbc400-53b7-11ea-871c-c41ce1eeb8b6.png">

That seems to be more of a Mac issue? I found [this thread](https://www.reddit.com/r/MacOS/comments/cgj1qs/cant_be_opened_because_apple_cannot_check_it_for/) & was able to open by right-clicking & clicking "open". Might be worth looking into how that might be avoided.

**Comment by marcgarreau** [comment]
Yeah, unfortunately that poor UX is something we've learned to live with in Mac-land. You'll see the same experience with even some well-known apps, not that it's a good excuse. It's on the nice-to-have list 😅 Agreed that the zip should be removed - will add a ticket.

**Comment by herman-rogers** [comment]
Just fyi - since this is closed - the zip still fails to open on mac but the dmg appears to work (ofc there's the security error but mac does that for literally everything)

**Comment by psytron** [comment]
confirmed zip 1.6.2 still fails with error "application can't be opened" on Mac OS Catalina 10.15.6
