### ISSUE TITLE
As a user, I want to see geth connection stats more prominently, so that I know how my node is performing at a glance.

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#71]

**Comment by ryanio** [comment]
I think the green dot is sufficient for this, anything other than green should mean "please pay attention, something is not 100%", then hovering over the dot can give you what is wrong. Also any error message from geth is displayed in the component under "Stopped/Started" status

**Comment by PhilippLgh** [comment]
implemented in https://github.com/PhilippLgh/ethereum-gui
