### ISSUE TITLE
bug: can start geth before a version is detected or installed

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#81]

**Comment by ryanio** [comment]
hm, the switch should be disabled if `client.release` in the store is null, which it is until a version is selected in VersionList

https://github.com/ethereum/grid-ui/blob/master/src/components/Nodes/index.js#L102

**Comment by marcgarreau** [comment]
I also tried this out and found that to be the case. I filed this ticket after @PhilippLgh reported it, so maybe he can clarify if I misunderstood the bug.

**Comment by ryanio** [comment]
sounds good, @PhilippLgh let us know if you can recreate
