### ISSUE TITLE
As a user, I want to sign transactions with Clef, so I can enjoy the added security

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#86]
**PRs:**

https://github.com/ethereum/grid/pull/227

**Repos:**

https://github.com/ryanio/grid-clef-plugin
https://github.com/ryanio/grid-clef-app

**Comment by ryanio** [comment]
Here are the Clef methods supported in Cleftron, as a guide of what kind of functionality we can begin to expect to support: https://github.com/holiman/Cleftron/blob/1800c4b14a635621dcf4136fc51bc3c8ee2c314f/src/main/modules/clef.js#L115

**Comment by ryanio** [comment]
grid-ui: https://github.com/ethereum/grid-ui/pull/58
grid: https://github.com/ethereum/grid/pull/191

ToDo:
* [ ] Data validation
* [ ] Data conversion (backend: hex<>frontend: numbers)
* [ ] Show ui_approveTx call_info warnings
* [ ] Clef settings: configDir, keystoreDIr

**Comment by marcgarreau** [comment]
closed via https://github.com/ethereum/grid/pull/227
