### ISSUE TITLE
As a user, I want to upload content to swarm, so that I can publish using decentralized storage

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/grid#97]

**Comment by evertonfraga** [comment]
Observations about swarm integration:
- Settings persistence would help testing a lot
- evaluate the net net of having `corsdomain=*` as default for swarm
- add Geth api to swarm config to enable ENS domains
- easier way to open devTools from the windows (could live on the menu)

**Comment by PhilippLgh** [comment]
feature cancelled
